export const surveyData = [
  {
    id: "depression",
    title: "Trắc nghiệm đánh giá trầm cảm",
    description:
      "Đánh giá mức độ trầm cảm thông qua bộ câu hỏi Beck Depression Inventory (BDI)",
    duration: "10-15 phút",
    questions: 21,
    status: "recommended",
    completions: 1234,
    averageRating: 4.8,
  },
  {
    id: "anxiety",
    title: "Trắc nghiệm đánh giá lo âu",
    description:
      "Đánh giá mức độ lo âu dựa trên thang đánh giá Hamilton Anxiety Rating Scale (HAM-A)",
    duration: "8-12 phút",
    questions: 14,
    status: "popular",
    completions: 2156,
    averageRating: 4.6,
  },
  {
    id: "stress",
    title: "Trắc nghiệm đánh giá stress",
    description: "Đánh giá mức độ stress dựa trên Perceived Stress Scale (PSS)",
    duration: "5-8 phút",
    questions: 10,
    status: "new",
    completions: 567,
    averageRating: 4.9,
  },
  {
    id: "personality",
    title: "Trắc nghiệm tính cách",
    description: "Đánh giá các đặc điểm tính cách dựa trên mô hình Big Five",
    duration: "15-20 phút",
    questions: 25,
    status: "popular",
    completions: 3421,
    averageRating: 4.7,
  },
  {
    id: "adhd",
    title: "Đánh giá ADHD",
    description: "Bộ câu hỏi sàng lọc rối loạn tăng động giảm chú ý (ADHD)",
    duration: "12-15 phút",
    questions: 18,
    status: "new",
    completions: 789,
    averageRating: 4.5,
  },
  {
    id: "eating",
    title: "Đánh giá rối loạn ăn uống",
    description:
      "Bộ công cụ sàng lọc các rối loạn về ăn uống và hành vi ăn uống",
    duration: "10-12 phút",
    questions: 16,
    status: "recommended",
    completions: 1567,
    averageRating: 4.6,
  },
];
